# Generated by Django 4.0.1 on 2022-08-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_todo_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
    ]
