# Generated by Django 4.0.1 on 2022-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_todo_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='body',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
